#!/bin/sh

## ================================================================
## Logtalk - Open source object-oriented logic programming language
## Release 2.32.1
##
## Copyright (c) 1998-2008 Paulo Moura.  All Rights Reserved.
## ================================================================

echo "Removing menu entries for some of the Logtalk integration scripts..."

if [ -x /usr/bin/update-menus ] ; then
	update-menus
fi

echo ""
echo "You have succesfully uninstalled Logtalk!"
echo ""
