#!/bin/sh

## ================================================================
## Logtalk - Open source object-oriented logic programming language
## Release 2.37.6
## 
## Copyright (c) 1998-2009 Paulo Moura.        All Rights Reserved.
## Logtalk is free software.  You can redistribute it and/or modify
## it under the terms of the "Artistic License 2.0" as published by 
## The Perl Foundation. Consult the "LICENSE.txt" file for details.
## ================================================================

echo ""
echo "Installed Logtalk on \"/usr/share\"."

chown -f -R -L root:root /usr/share/logtalk

echo ""
echo "Installing and registering Logtalk online documentation..."

if [ "$1" = "configure" ] ; then
	if which install-docs > /dev/null 2>&1 ; then
		install-docs -i /usr/share/doc-base/logtalk-docs
	fi
fi

chown -f -R -L root:root /usr/share/doc/logtalk

echo "Adding menu entries for some of the Logtalk integration scripts..."

if [ -x /usr/bin/update-menus ] ; then
	update-menus
fi

echo
echo "Links to the \"cplgtdirs\", \"lgt2pdf\", \"lgt2html\", \"lgt2xml\", and "
echo "\"lgt2txt\" scripts have been created on \"/usr/bin\"."
echo
echo "The following integration scripts are installed for running Logtalk"
echo "with selected back-end Prolog compilers:"
echo
echo "* B-Prolog (version 7.1 or later):         bplgt"
echo "* Ciao (version 1.10):                     ciaolgt    (first run must use sudo)"
echo "* CxProlog (version 0.97.2 or later):      cxlgt"
echo "* ECLiPSe (versions 5.10, 6.0):            eclipselgt"
echo "* GNU Prolog (version 1.3.1 or later):     gplgt"
echo "* K-Prolog (versions 5.1.5, 6.0.4):        plclgt"
echo "* Qu-Prolog (version 8.9 or later):        qplgt"
echo "* Quintus Prolog (version 3.5):            quintuslgt (requires patching Logtalk)"
echo "* SICStus Prolog (versions 3.12.x, 4.0.x): sicstuslgt"
echo "* SWI-Prolog (version 5.6.44 or later):    swilgt"
echo "* XSB (version 3.2 or later):              xsblgt     (first run must use sudo)"
echo "* XSB 64 bits (version 3.2 or later):      xsb64lgt   (first run must use sudo)"
echo "* XSB MT (version 3.2 or later):           xsbmtlgt   (first run must use sudo)"
echo "* XSB MT 64 bits (version 3.2 or later):   xsbmt64lgt (first run must use sudo)"
echo "* YAP (version 5.1.3 or later):            yaplgt"
echo
echo "The Prolog integration scripts can be found on \"/usr/bin\"."
echo "Make sure that the Prolog compilers are properly installed and available"
echo "on your execution path."
echo
echo "Integration with Quintus Prolog requires manual patches that render"
echo "Logtalk incompatible with all the other compilers."
echo
echo "Users should run the \"cplgtdirs\" shell script once before using the"
echo "integration scripts."
echo
echo "If you get an unexpected failure when using one of the Prolog integration"
echo "scripts, consult see the \"/usr/share/logtalk/configs/NOTES.txt\" file"
echo "for compatibility notes."
echo
if [ -x /usr/bin/update-mime-database ]; then
	mkdir -p /usr/share/mime/packages
	rm -f /usr/share/mime/packages/logtalk.xml
	cp /usr/share/lgt2376/scripts/freedesktop/logtalk.xml /usr/share/mime/packages/logtalk.xml
	update-mime-database /usr/share/mime
	echo "Added the Logtalk mime-type to the Shared MIME-info Database."
	echo
fi
echo "Logtalk basic installation completed."
echo
