#!/bin/bash

## =================================================================
## Logtalk - Object oriented extension to Prolog
## Release 2.29.6
##
## Copyright (c) 1998-2007 Paulo Moura.  All Rights Reserved.
## =================================================================

echo ""
echo "Uninstalling and de-registering Logtalk online documentation..."
echo ""

if [ "$1" = remove -o "$1" = upgrade ]; then
	if which install-docs >/dev/null 2>&1; then
		install-docs -r logtalk-docs
	fi
fi

echo ""
echo "Removing default Logtalk environment variable definitions..."
echo ""

sed -e '/# Logtalk environment variables default values/{N;N;N;d;}' -i /etc/profile

echo ""
echo "You have succesfully uninstalled Logtalk!"
echo ""
