#!/bin/sh

## ================================================================
## Logtalk - Open source object-oriented logic programming language
## Release 2.41.0
## 
## Copyright (c) 1998-2010 Paulo Moura.        All Rights Reserved.
## Logtalk is free software.  You can redistribute it and/or modify
## it under the terms of the "Artistic License 2.0" as published by 
## The Perl Foundation. Consult the "LICENSE.txt" file for details.
## ================================================================

echo ""
echo "Uninstalling and de-registering Logtalk online documentation..."

if [ "$1" = "remove" ] || [ "$1" = "upgrade" ] ; then
	if which install-docs > /dev/null 2>&1 ; then
		install-docs -r logtalk-docs
	fi
fi

echo ""
echo "Removing Logtalk integration and documentation scripts..."

rm -rf /usr/share/logtalk/bin
