#!/bin/sh

# [Gedit Tool]
# Comment=Generate TEXT documentation for the current Logtalk source file
# Input=document
# Name=Generate Logtalk TEXT documentation
# Applicability=titled
# Output=output-panel

cd "$GEDIT_CURRENT_DOCUMENT_DIR"
FILE=`basename "$GEDIT_CURRENT_DOCUMENT_NAME" .lgt`
yaplgt -g "logtalk_compile($FILE), halt."
lgt2txt
