#!/bin/sh

# [Gedit Tool]
# Comment=Compile the current Logtalk source file
# Input=document
# Name=Logtalk: compile to disk
# Applicability=titled
# Output=output-panel

cd "$GEDIT_CURRENT_DOCUMENT_DIR"
FILE=`basename "$GEDIT_CURRENT_DOCUMENT_NAME" .lgt`
yaplgt -g "logtalk_compile($FILE), halt."
