#!/bin/sh

# [Gedit Tool]
# Name=Logtalk: compile to disk
# Comment=Compile the current Logtalk source file
# Shortcut=
# Input=document
# Output=output-panel
# Applicability=titled

cd "$GEDIT_CURRENT_DOCUMENT_DIR"
FILE=`basename "$GEDIT_CURRENT_DOCUMENT_NAME" .lgt`
yaplgt -g "logtalk_compile($FILE), halt."
