.TH ciaolgt 1 "June 10, 2010" "Logtalk 2.40.0" "Logtalk Documentation"

.SH NAME
ciaolgt \- Logtalk integration script for Ciao Prolog

.SH SYNOPSIS
.B ciaolgt
[
.BI \-e\ goal
]

.SH DESCRIPTION
\f3ciaolgt\f1 is a Logtalk integration script for Ciao Prolog. It automatically loads the Ciao Prolog config file, the Logtalk compiler and runtime, and the Logtalk default table of library names and paths.

.SH OPTIONS
.TP
.BI \-e\ goal
Initialization goal, to be executed after Logtalk startup.

.SH ENVIRONMENT
.TP
.B LOGTALKHOME
Specifies the location of the Logtalk installation.
.TP
.B LOGTALKUSER
Specifies the location of the Logtalk user folder.

.SH FILES
.TP
.BI $LOGTALKHOME/integration/logtalk_ciao.pl
Prolog file used for loading the necessary files for starting Logtalk using Ciao Prolog as the back-end compiler.
.TP
.BI $LOGTALKHOME/configs/ciao.pl\ $LOGTALKHOME/configs/ciao_aux.pl
The Ciao Prolog config files.
.TP
.BI $LOGTALKHOME/compiler/logtalk.pl
The Logtalk compiler and runtime file.
.TP
.BI $LOGTALKUSER/libpaths/libpaths.pl
The default table of library names and paths.

.SH "SEE ALSO"
The Logtalk website at http://logtalk.org/
.PP
The Logtalk User and Reference Manuals at $LOGTALKHOME/manuals/index.html
.PP
The Ciao Prolog website at http://www.clip.dia.fi.upm.es/Software/Ciao/index.html
.PP
cplgtdirs(1),\ logtalk_select(1),\ logtalk_backend_select(1)

.SH AUTHOR
Paulo Moura <pmoura@logtalk.org>

.SH COPYRIGHT
Copyright (c) 1998-2010 Paulo Moura.
